name: pinesphere_erp
description: Pinesphere AI Training Institute ERP mobile-first app.
publish_to: 'none'

version: 1.0.3+8

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.6.0
  flutter_svg: ^2.0.17
  flutter_animate: ^4.5.0
  glassmorphism: ^3.0.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.0
  uuid: ^4.5.3
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  intl: 0.20.2
  better_player_plus: ^1.1.5
  video_player: ^2.10.0
  file_picker: ^10.3.2
  http_parser: ^4.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/app_icon.png
  android: true
  ios: false